---
title: "linear model more stuff"
output: html_document
---


```{r}
library(ElemStatLearn)
library(car)
library(corrplot)
library(leaps)
library(glmnet)
library(caret)
data("prostate")
str(prostate)
```

```{r}
plot(prostate)
plot(prostate$gleason)
table(prostate$gleason)
boxplot(prostate$lpsa~prostate$gleason)
prostate$gleason<-ifelse(prostate$gleason== 6, 0, 1) #because the number of gleason's value 8 and 9 is a few.
table(prostate$gleason)
p.cor=cor(prostate)
corrplot.mixed(p.cor)
train<-subset(prostate, train==T)[,1:9] #dividing data into two sets, test and train
str(train)
test<-subset(prostate, train=F)[,1:9]
str(test)
subfit<-regsubsets(lpsa~., data=train)
b.sum<-summary(subfit)
which.min(b.sum$bic) # 3 varaibles are good to be included in our model.
plot(b.sum$bic, type="l")
plot(subfit, scale="bic", main="best subset features")
ols<-lm(lpsa~lcavol+lweight+gleason, data=train)
plot(ols$fitted.values, train$lpsa,xlab="predicted", ylab="actual", main="predict vs actual")
pred.subfit<-predict(ols, newdata=test)
plot(pred.subfit, test$lpsa, xlab="predicted", ylab="actual", main="predicted vs acutal")
resid.subfit<-test$lpsa-pred.subfit
mean(resid.subfit^2) #MSE
```